

@rootApi = http://localhost:8000
@userApi = {{rootApi}}/api/v1/user
### server testing

@burrowAPI = {{rootApi}}/api/v1/burrow



@bookApi={{rootApi}}/api/v1/book


@reviewApi={{rootApi}}/api/v1/review


GEt {{rootApi}}


# ============user Api
### get user
GET {{userApi}}




### send

POSt {{userApi}}
Content-Type: application/json

{
    "role":"admin",
    "fName": "Sam",
    "lName": "Smith",
    "phone":"0404040404",
    "address":"NSW",
    "email": "sushan.maharjan18@gmail.com",
    "password": "67890"
    
}
\





# ============ Book api 
### fetch all book
GET {{bookApi}}
Authorization: 64aa149febfeaf4cccb5ac27
# ======== burrow api
### fetch
GET  {{burrowAPI}}
Authorization: 64aa149febfeaf4cccb5ac27

###
POST {{burrowAPI}}
Content-Type: application/json

{
    "bookId":"acghauicua678",
    "BookName": "Sushan Maharjan",
    "thumbnail": "http://...",
    "userId": "dfghjkl",
    "userName": "how to code",
    "returnDate": "23 jan"

}
###
PUT {{burrowAPI}}
Authorization: 64a8e1fc381925c4b42452b0



# review api 


### get reviews

GET {{reviewApi}}